Создание резинового макета
Evgenrol/admin-panel-makeup pull request #1
Opened 2022-01-30 15:58 UTC by Evgenrol

Задание 1. Не удалось выравнять searsh как в макете

2022-02-01 20:53 UTC, Muslik requested changes
Не соответсвует макету. Таблица должны доходить до конца страницы. Цвет шрифта не как в макете. Высота header, footer таблицы не по макету

2022-02-02 07:37 UTC, Evgenrol commented
Исправила размеры  header, footer. Так же размер таблицы, чтобы до конца, но все равно какой-то отступ присутствует(не разобралась как убрать его). Так же цвет шрифта по какой-то причине не меняется.

2022-02-02 08:14 UTC, Evgenrol commented
> Не соответсвует макету. Таблица должны доходить до конца страницы. Цвет шрифта не как в макете. Высота header, footer таблицы не по макету

Убран отступ снизу страницы. Но почему не меняется цвет шрифта так и осталось загадкой)

2022-02-04 21:42 UTC, Muslik approved these changes
Good

2022-02-06 14:21 UTC, merged