add searsh-bar
Evgenrol/admin-panel-makeup pull request #4
Opened 2022-02-16 08:17 UTC by Evgenrol

2022-02-20 03:55 UTC, Muslik requested changes
Поработайте над именованием классов. Если будут вопросы, напишите мне в телеге, можем созвониться, расскажу подробнее

2022-02-20 03:55 UTC, Muslik commented on blocks/ui-kit.html
> +        <div class="search-row__filled">
Опять же этот блок ничем не отличается от блока search-row__empty, а значит классы должны быть одинаковыми

2022-02-20 03:55 UTC, Muslik commented on blocks/ui-kit.html
> +        <div class="search-row__filled">
У вас все что там есть это отступ снизу. Это решается проще. Класс .input-row

Далее если по бэм, то вы можете задать этом блоку класс элемента от родителя, в вашем случае .search-row__input-row

Далее в стилях уже зададите отступы:
.search-row__input-row { margin-bottom: 16px;}
.search-row__input-row:last-child { margin-bottom: 0;}

Что мы получаем в итоге. Сам блок .input-row - независимый. У него нет никаких отступов изначально. И я его могу вставить куда угодно на страницу. Получается я его вставил в блок .search-row и search-row говорит что теперь .input-row является его элементом и задает ему отступы

2022-02-20 03:55 UTC, Muslik commented on blocks/ui-kit.html
> +            onclick="document.getElementById
За это снова отдельный лайк. :)

2022-02-21 11:49 UTC, Evgenrol commented on blocks/ui-kit.html
> +        <div class="search-row__filled">
Спасибо, внесла изменения. Стало понятней по БЭМ.

2022-02-21 11:49 UTC, Evgenrol commented
Внесла корректировки

2022-02-21 12:04 UTC, Evgenrol commented on blocks/ui-kit.html
> +            onclick="document.getElementById
Спасибо) тоже понравился способ

2022-02-22 22:35 UTC, Muslik approved these changes

2022-02-23 08:16 UTC, merged